- name: Create elixir group
  group:
    name: "{{ elixir_group }}"
  become: true

- name: Create elixir user
  user:
    name: "{{ elixir_user }}"
    group: "{{ elixir_group }}"
  become: true

- name: Install Erlang 20
  pkgng:
    name: "{{ item }}"
  with_items:
    - erlang
    - erlang-runtime20
  become: true

- shell: cp -r /usr/local/lib/erlang20/bin/* /usr/local/bin/
  become: true

- name: Ensure elixir directory exists
  file:
    path: /usr/local/share/elixir
    state: directory
  become: true

- name: Get elixir (precompiled)
  get_url:
    url: https://github.com/elixir-lang/elixir/releases/download/v1.5.1/Precompiled.zip
    dest: /tmp/elixir.zip
  become: true

- name: Extract elixir
  unarchive:
    src: /tmp/elixir.zip
    remote_src: true
    dest: /usr/local/share/elixir
    owner: "{{ elixir_user }}"
    group: "{{ elixir_group }}"
  become: true

- name: Set symlinks for elixir
  file:
    src: /usr/local/share/elixir/bin/{{ item }}
    dest: /usr/local/bin/{{ item }}
    state: link
    owner: "{{ elixir_user }}"
    group: "{{ elixir_group }}"
  with_items:
    - elixir
    - mix
    - iex
    - elixirc
  become: true

- name: Install git
  pkgng:
    name: git
  become: true

- name: Download dialyxir
  git:
    repo: https://github.com/jeremyjh/dialyxir
    dest: /usr/local/dialyxir
  become: true

- file:
    path: /usr/local/dialyxir
    state: directory
    owner: "{{ elixir_user }}"
    group: "{{ elixir_group }}"
  become: true

- name: Install dialyxir
  command: "{{ item }}"
  args:
    chdir: /usr/local/dialyxir
  with_items:
    - mix local.hex --force
    - mix local.rebar --force
    - mix clean
    - mix compile
    - mix archive.build
    - mix archive.install --force
  environment:
    MIX_ENV: prod
  become: true
  become_user: "{{ elixir_user }}"
