- template:
    src: pg_hba.conf.j2
    dest: "{{ pg_conf_path}}/pg_hba.conf"
    mode: 0600
  become: true
  notify: reload postgres

- template:
    src: postgresql.conf.j2
    dest: "{{ pg_conf_path }}/postgresql.conf"
    mode: 0600
  become: true
  notify: restart postgres
