- template:
    src: pg_hba.conf.j2
    dest: /var/db/postgres/data96/pg_hba.conf
    mode: 0600
  become: true
  notify: reload postgres

- template:
    src: postgresql.conf.j2
    dest: /var/db/postgres/data96/postgresql.conf
    mode: 0600
  become: true
  notify: restart postgres
