helix_database_username: helix
helix_database_password: "{{ private_helix_database_password }}"
helix_database_host: "{{ ansible_host }}"
helix_database_pool_size: 3
helix_database_prefix: interactive

helix_environment:
  HELIX_NODE_NAME: "{{ inventory_hostname }}"
  HELIX_CLUSTER_COOKIE: "{{ private_helix_cluster_cookie }}"
  HELIX_ENDPOINT_SECRET_KEY: "{{ private_helix_endpoint_secret_key }}"
  HELIX_ENDPOINT_URL: "{{ helix_endpoint_url }}"
  HELIX_DB_PREFIX: "{{ helix_database_prefix }}"
  HELIX_DB_USER: "{{ helix_database_username }}"
  HELIX_DB_PASS: "{{ helix_database_password }}"
  HELIX_DB_HOST: "{{ helix_database_host }}"
  HELIX_DB_POOL_SIZE: "{{ helix_database_pool_size }}"
  REPLACE_OS_VARS: "true"
  MIX_ENV: "prod"
