# Play to deploy chat
- name: Setup Chat
  hosts: chat

  roles:
    - {role: common, tags: common}
    - {role: docker, tags: docker}
    - {role: docker_compose, tags: docker_compose}
    - {role: mattermost, tags: mattermost}
    # - {role: pf, tags: pf}
