- name: Setup Helix server
  hosts: helix

  environment: "{{ helix_environment }}"

  # TODO: Helix does not need elixir.

  roles:
    - {role: common, tags: common}
    - {role: elixir, tags: elixir}
    - {role: helix, tags: helix}
    # - {role: pf, tags: pf}
