- name: Setup HEBorn migration
  hosts: migration
  
  environment: "{{ migration_environment }}"
  
  roles:
    - {role: common, tags: common}
    - {role: nginx, tags: nginx}
    - {role: elixir, tags: elixir}
    - {role: migration, tags: migration}
    # - {role: pf, tags: pf}
