haproxy_user: haproxy
haproxy_group: haproxy

haproxy_chroot_path: /var/lib/haproxy
haproxy_socket_path: /var/run/haproxy

haproxy_maxconn: 5000

haproxy_nbproc: 1
haproxy_cpumap: |
  cpu-map 1 0

haproxy_timeout_connect: 5s
haproxy_timeout_client: 30s
haproxy_timeout_client_fin: 30s
haproxy_timeout_server: 30s
haproxy_timeout_tunnel: 10m

haproxy_defaults: |
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect {{ haproxy_timeout_connect }}
  timeout client {{ haproxy_timeout_client }}
  timeout client-fin {{ haproxy_timeout_client_fin }}
  timeout server {{ haproxy_timeout_server }}
  timeout tunnel {{ haproxy_timeout_tunnel }}

haproxy_ca_base: "/etc/ssl/certs"
haproxy_crt_base: "/etc/ssl/private"
haproxy_default_ciphers: "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS"

haproxy_global: |
  log /dev/log local0
  chroot {{ haproxy_chroot_path }}
  stats socket {{ haproxy_socket_path }}/admin.sock mode 660 level admin
  stats timeout 30s
  user {{ haproxy_user }}
  group {{ haproxy_group }}
  daemon
  ca-base {{ haproxy_ca_base }}
  crt-base {{ haproxy_crt_base }}
  ssl-default-bind-ciphers {{ haproxy_default_ciphers }}
  tune.ssl.default-dh-param 2048

haproxy_listen: |
  bind *:{{ haproxy_stats_port }}
  stats enable
  stats uri /
  stats hide-version
  stats auth {{ haproxy_stats_user }}:{{ haproxy_stats_pass }}

