- name: Add deployer user
  user:
    name: "{{ deployer_user }}"
  become: true

- name: Add heborn user
  user:
    name: "{{ heborn_user }}"
  become: true

- name: Ensure .ssh directory for heborn user
  file:
    path: "/home/{{ heborn_user }}/.ssh"
    state: directory
    recurse: true
    owner: "{{ heborn_user }}"
    group: "{{ heborn_group }}"
  become: true

- name: Copy deployer public key
  authorized_key:
    user: "{{ deployer_user }}"
    state: present
    key: "{{ lookup('file', '../../deployer/files/deployer_production.pub') }}"
  become: true
  become_user: "{{ deployer_user }}"

- name: Install required stuff
  pkgng:
    name: "{{ item }}"
  with_items:
    - py27-boto3
    - py27-botocore
  become: true

- include_role:
    name: heborn
    tasks_from: deploy
  when:
    - deploy is defined
  tags:
    - deploy
