cloud_gcp_rcconf: |
  google_accounts_manager_enable="YES"
  google_startup_enable="YES"
  ntpd_sync_on_start="YES"
  ifconfig_DEFAULT="SYNCDHCP mtu 1460"
  ntpd_enable="YES"
  sshd_enable="YES"
  panicmail_autosubmit="YES"

cloud_ovh_rcconf: |
  ifconfig_vtnet0="DHCP"

cloud_gcp_bootloader: |
  hw.vtnet.mq_disable=1
  aesni_load="YES"
  nvme_load="YES"
  kern.timecounter.hardware=ACPI-safe

cloud_ovh_bootloader: |
  geom_mirror_load="YES"
  kern.geom.label.disk_ident.enable="0"
  kern.geom.label.gptid.enable="0"
  zfs_load="YES"

# Whose idea was to use Yaml and Jinja? I miss Chef...
cloud_user: "{{ 'renato' if provider is not defined else ('freebsd' if provider == 'ovh' else ('renato' if provider == 'gcp' else 'root')) }}"

cloud_private_key: "{{ '~/.ssh/ovh' if provider == 'ovh' else ('~/.ssh/google_compute_engine' if provider == 'gcp' else '~/.ssh/digital_ocean') }}"
external_network_interface: "vtnet0"
internal_network_interface: "vtnet1"

cloud_ssh_users: "{{ cloud_user }}"
