- name: Force update pkg
  shell: pkg clean -ay && pkg update -f
  become: true
  changed_when: false
  when: "'freebsd' in group_names"

- name: Install some basic stuff
  pkgng:
    name: "{{ item }}"
  with_items:
    - wget
    - ca_root_nss
    - bash
    - sudo
  when: "'freebsd' in group_names"
  become: true
- apt:
    name: "{{ item }}"
  with_items:
    - ca-certificates
  become: true
  when: "'debian' in group_names"

- name: Add sudoers template
  template:
    src: sudoers.j2
    dest: "{{ sudoers_path }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0440
    backup: yes
  become: true

- name: Ensure ansible facts directory exists
  file:
    path: /etc/ansible/facts.d
    recurse: yes
    state: directory
  become: true

- name: Track these tasks for changes
  include_role:
    name: utils
    tasks_from: tracker
  vars:
    from_role: common
    track_file: configure
